language: r

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

sudo: false

os: osx
compiler: clang
    
cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
