language: r

# required for bedr
before_install:
  - brew update
  - brew install homebrew/science/bedops
  - brew install homebrew/science/bedtools
  - brew install homebrew/science/htslib

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

sudo: false

os: osx
compiler: clang
bioc_packages:
  - IRanges
  - GenomicRanges

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
